import "./globals.css";
import AuthContext from "./context/AuthContext";
import ToasterContext from "./context/ToasterContext";
import LayoutComponent from "./components/layout/LayoutComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ToasterContext />
          <LayoutComponent>{children}</LayoutComponent>
        </AuthContext>
      </body>
    </html>
  );
}
